var countries = {
"alaska" : {"cont"  : "na",
		   "borders" : ["northwestTerritory", "alberta", "kamchatka"],
		   "army" : "25",
		   "owner"   : "",
		   "attack"  : "",
		},
"northwestTerritory" : {"cont" : "na", 
		   "borders" : ["alaska", "greenland", "ontario", "alberta"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"alberta" : {"cont" : "na",
		   "borders" : ["alaska", "northwestTerritory", "ontario", "westernUnitedStates"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"ontario" : {"cont" : "na",
		   "borders" : ["easternUnitedStates", "westernUnitedStates", "alberta", "northwestTerritory", "greenland", "quebec"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"quebec" : {"cont" : "na",
		   "borders" : ["easternUnitedStates", "ontario", "greenland"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"greenland" : {"cont" : "na",
		   "borders" : ["northwestTerritory", "ontario", "quebec", "iceland"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"westernUnitedStates" : {"cont" : "na",
		   "borders" : ["alberta", "ontario", "easternUnitedStates", "centralAmerica"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"easternUnitedStates" : {"cont" : "na", 
		   "borders" : ["westernUnitedStates", "ontario", "quebec"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"centralAmerica" : {"cont" : "na",
		   "borders" : ["venezuela", "westernUnitedStates", "easternUnitedStates"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"venezuela" : {"cont" : "sa",
		   "borders" : ["brazil", "argentina", "centralAmerica"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"brazil" : {"cont" : "sa", 
		   "borders" : ["argentina", "venezuela", "northAfrica"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"argentina" : {"cont" : "sa",
		   "borders" : ["brazil", "venezuela"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"northAfrica" : {"cont" : "afr",
		   "borders" : ["westernEurope", "southernEurope", "egypt", "congo", "brazil"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"egypt" : {"cont" : "afr",
		   "borders" : ["middleEast", "eastAfrica", "northAfrica", "southernEurope"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"congo" : {"cont" : "afr",
		   "borders" : ["southAfrica", "eastAfrica", "egypt", "northAfrica"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"eastAfrica" : {"cont" : "afr", 
		   "borders" : ["madagascar", "southAfrica", "congo", "egypt"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"madagascar" : {"cont" : "afr",
		   "borders" : ["eastAfrica", "southAfrica"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"southAfrica" : {"cont" : "afr",
		   "borders" : ["madagascar", "eastAfrica", "congo"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"iceland" : {"cont" : "eur",
		   "borders" : ["greenland", "greatBritain"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"greatBritain" : {"cont" : "eur",
		   "borders" : ["iceland", "scandinavia", "northernEurope", "westernEurope"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"scandinavia" : {"cont" : "eur",
		   "borders" : ["ukraine", "northernEurope", "greatBritain"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"northernEurope" : {"cont" : "eur", 
		   "borders" : ["southernEurope", "westernEurope", "greatBritain", "scandinavia", "ukraine"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"westernEurope" : {"cont" : "eur",
		   "borders" : ["northAfrica", "southernEurope", "northernEurope", "greatBritain"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"southernEurope" : {"cont" : "eur",
		   "borders" : ["egypt", "northernEurope", "northAfrica", "westernEurope", "ukraine"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"ukraine" : {"cont" : "eur",
		   "borders" : ["russia", "afghanistan", "middleEast", "southernEurope", "northernEurope", "scandinavia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"russia" : {"cont" : "asia",
			"borders" : ["ukraine", "afghanistan", "siberia"],
			"army" : "",
		    "owner":"",
			"attack":"",
			},
"siberia" : {"cont" : "asia",
		   "borders" : ["russia", "afghanistan", "china", "mongolia", "irkutsk", "yakutsk"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"yakutsk" : {"cont" : "asia", 
		   "borders" : ["siberia", "irkutsk", "kamchatka"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"kamchatka" : {"cont" : "asia",
		   "borders" : ["yakutsk", "irkutsk", "mongolia", "japan", "alaska"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"irkutsk" : {"cont" : "asia", 
		   "borders" : ["siberia", "yakutsk", "kamchatka", "mongolia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"mongolia" : {"cont" : "asia", 
		   "borders" : ["china", "siberia", "irkutsk", "kamchatka", "japan"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"japan" : {"cont" : "asia",
		   "borders" : ["mongolia", "kamchatka"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"china" : {"cont" : "asia", 
		   "borders" : ["siam", "india", "afghanistan", "siberia", "mongolia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"afghanistan" : {"cont" : "asia",
		   "borders" : ["middleEast", "ukraine", "russia", "siberia", "china", "india"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"middleEast" : {"cont" : "asia",
		   "borders" : ["egypt", "ukraine","afghanistan", "india"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"india" : {"cont" : "asia",
		   "borders" : ["middleEast", "afghanistan", "china", "siam"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"siam" : {"cont" : "asia",
		   "borders" : ["china", "india","indonesia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"indonesia" : {"cont" : "aus",
		   "borders" : ["westernAustralia", "newGuinea", "siam"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"newGuinea" : {"cont" : "aus",
		   "borders" : ["easternAustralia", "westernAustralia", "indonesia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"westernAustralia" : {"cont" : "aus", 
		   "borders" : ["easternAustralia", "newGuinea", "indonesia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
		},
"easternAustralia" : {"cont" : "aus",
		   "borders" : ["lotr", "newGuinea", "westernAustralia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
},
"lotr" : {"cont" : "aus",
		   "borders" : ["easternAustralia"],
		   "army"    : "",
		   "owner"   : "",
		   "attack"  : "",
}
}